### PR TITLE
Update to - reusable workflows

### PR DESCRIPTION
**Pull request by SomilGanguly**

### CODE REVIEW

**Comment by daltondhcp** [comment]
As discussed earlier today, please incorporate https://github.com/Azure/AzOps/issues/383 in this PR as well.

**Comment by jsandquist** [comment]
Please consider updating also the 'update' workflow - specifically on this line https://github.com/SomilGanguly/AzOps-Accelerator/blob/sogangul-AzOpsAccelerator-pipelineRevamp/.github/workflows/update.yml#L86

or we will miss out on the `.templates` folder. Similar to https://github.com/Azure/AzOps-Accelerator/pull/106/files I assume.

**Comment by daltondhcp** [comment]
@Jefajers, please take a look at this from a doc perspective.

**Comment by daltondhcp** [comment]
I took the liberty of incorporating the change described in https://github.com/Azure/AzOps/issues/384 for both the Actions and ADO pipelines.

**Review by daltondhcp — APPROVED** [review]
image

**Pull request merged**
