### PR TITLE
Add redeploy pipeline

### PR DESCRIPTION
**Pull request by SimonWahlin**
Add pipeline that will redeploy all files in specified path.

Closes https://github.com/Azure/AzOps/issues/593

### CODE REVIEW

**Comment by daltondhcp** [comment]
Looks great! Are you able to create a GH actions version as well?

**Comment by SimonWahlin** [comment]
Sure!

**Comment by SimonWahlin** [comment]
Added github pipeline and also added the customSorting feature to the github workflows.

Let me know what you think

**Comment by daltondhcp** [comment]
Verified in GitHub Actions successfully now ✅ 

Does it make sense to also allow individual templates in the path as well to be able to redeploy a single resource? I can see some use cases where that would come handy.

**Comment by SimonWahlin** [comment]
Yes, I think that makes sense

**Review by daltondhcp — APPROVED** [review]
LGTM 🚢 
Would be great if you could push some simple doc notes about this as well when you have time.

**Comment by SimonWahlin** [comment]
Simple doc notes added in https://github.com/Azure/AzOps/pull/727

**Pull request merged**
